Refactor artefact metadata routes and rendering
open-component-model/delivery-dashboard pull request #114
Opened 2024-07-11 11:09 UTC by 8R0WNI3

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-07-11 16:49 UTC, zkdev requested changes

2024-07-12 15:26 UTC, 8R0WNI3 commented on src/api.js
> +  enableCache,
Agree 👍🏼

2024-07-13 20:49 UTC, zkdev commented on src/components/dependencies/ComplianceCells.js
> +            label='OS Info Loading...'
rather use circularprogress or skeleton

2024-07-13 20:51 UTC, zkdev requested changes

2024-07-13 20:51 UTC, zkdev commented on src/components/dependencies/ComplianceCells.js
> +  if (isLoading) return 'Loading...'
also here, rather use a loading animation than static text

2024-07-13 20:51 UTC, zkdev commented on src/components/dependencies/ComplianceCells.js
> +            return structureInfo.data.package_name === 'golang-runtime'
factor out golang package name to const, please

2024-07-15 09:55 UTC, merged